export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const ORDER_CONFIRM = 'ORDER_CONFIRM';
export const ORDER_START = 'ORDER_START';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_TABLES_START = 'FETCH_TABLES_START';
export const FETCH_TABLES_SUCCESS = 'FETCH_TABLES_SUCCESS';
export const FETCH_TABLES_FAIL = 'FETCH_TABLES_FAIL';
export const FETCH_CAPACITY = 'FETCH_CAPACITY';
export const FETCH_SLOTS = 'FETCH_SLOTS';

export const BOOK_TABLE_START = 'BOOK_TABLE_START';
export const BOOK_TABLE_SUCCESS = 'BOOK_TABLE_SUCCESS';
export const BOOK_TABLE_FAIL = 'BOOK_TABLE_FAIL';
export const BOOK_TABLE_INIT = 'BOOK_TABLE_INIT';

export const FETCH_BOOKING_START = 'FETCH_BOOKING_START';
export const FETCH_BOOKING_SUCCESS = 'FETCH_BOOKING_SUCCESS';
export const FETCH_BOOKING_FAIL = 'FETCH_BOOKING_FAIL';
export const BOOKING_CONFIRM = 'BOOKING_CONFIRM';
export const BOOKING_START = 'BOOKING_START';

export const FETCH_ALL_ORDERS_START = 'FETCH_ALL_ORDERS_START';
export const FETCH_ALL_ORDERS_SUCCESS = 'FETCH_ALL_ORDERS_SUCCESS';
export const FETCH_ALL_ORDERS_FAIL = 'FETCH_ALL_ORDERS_FAIL';
export const FETCH_ALL_BOOKING_START = 'FETCH_ALL_BOOKING_START';
export const FETCH_ALL_BOOKING_SUCCESS = 'FETCH_ALL_BOOKING_SUCCESS';
export const FETCH_ALL_BOOKING_FAIL = 'FETCH_ALL_BOOKING_FAIL';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_MANAGER = 'SET_MANAGER';